/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BookingStatus = { 'scheduled' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface ConsultationBooking {
  'id' : bigint,
  'status' : BookingStatus,
  'userName' : string,
  'serviceType' : ConsultationType,
  'contact' : string,
  'userId' : Principal,
  'preferredDate' : string,
  'notes' : string,
}
export type ConsultationType = { 'webDesign' : null } |
  { 'investmentPlanning' : null };
export interface Enquiry {
  'id' : bigint,
  'contactInfo' : string,
  'enquiryType' : EnquiryType,
  'userId' : Principal,
  'message' : string,
  'timestamp' : Time,
}
export type EnquiryType = {
    'realEstate' : { 'buy' : null } |
      { 'land' : null } |
      { 'rent' : null } |
      { 'sell' : null } |
      { 'farmhouse' : null }
  } |
  {
    'webDesign' : { 'websiteDev' : null } |
      { 'businessPromo' : null } |
      { 'socialMedia' : null }
  } |
  {
    'education' : { 'legal' : null } |
      { 'career' : null } |
      { 'guidance' : null }
  } |
  {
    'investmentPlanning' : { 'startup' : null } |
      { 'business' : null } |
      { 'property' : null } |
      { 'fundManagement' : null }
  } |
  {
    'interiorDecor' : { 'pvcPanel' : null } |
      { 'ceiling' : null } |
      { 'homeInterior' : null }
  };
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'total' : bigint,
  'userId' : Principal,
  'timestamp' : Time,
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export interface Product {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : ProductCategory,
  'price' : bigint,
}
export type ProductCategory = { 'home' : null } |
  { 'local' : null } |
  { 'fashion' : null } |
  { 'electronics' : null };
export interface PropertyListing {
  'id' : bigint,
  'status' : { 'rented' : null } |
    { 'active' : null } |
    { 'sold' : null },
  'title' : string,
  'contact' : string,
  'propertyType' : PropertyType,
  'owner' : Principal,
  'description' : string,
  'areaSize' : bigint,
  'budget' : bigint,
  'location' : string,
}
export type PropertyType = { 'buy' : null } |
  { 'land' : null } |
  { 'rent' : null } |
  { 'sell' : null } |
  { 'farmhouse' : null };
export type Time = bigint;
export interface UserProfile {
  'contact' : string,
  'name' : string,
  'walletBalance' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, ProductCategory, bigint, string, string, bigint],
    bigint
  >,
  'addPropertyListing' : ActorMethod<
    [string, PropertyType, string, bigint, bigint, string, string],
    bigint
  >,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookConsultation' : ActorMethod<
    [ConsultationType, string, string, string, string],
    bigint
  >,
  'clearMyCart' : ActorMethod<[], undefined>,
  'createOrder' : ActorMethod<[], bigint>,
  'getAllBookings' : ActorMethod<[], Array<ConsultationBooking>>,
  'getAllEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllPropertyListings' : ActorMethod<[], Array<PropertyListing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFilteredProductsByCategory' : ActorMethod<
    [ProductCategory],
    Array<Product>
  >,
  'getFilteredPropertiesByBudget' : ActorMethod<
    [bigint, bigint],
    Array<PropertyListing>
  >,
  'getMyBookings' : ActorMethod<[], Array<ConsultationBooking>>,
  'getMyCart' : ActorMethod<[], Array<CartItem>>,
  'getMyEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyPropertyListings' : ActorMethod<[], Array<PropertyListing>>,
  'getSortedProductsByPrice' : ActorMethod<[boolean], Array<Product>>,
  'getSortedPropertiesByBudget' : ActorMethod<
    [boolean],
    Array<PropertyListing>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitEnquiry' : ActorMethod<[EnquiryType, string, string], bigint>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProductStock' : ActorMethod<[bigint, bigint], undefined>,
  'updatePropertyStatus' : ActorMethod<
    [bigint, { 'rented' : null } | { 'active' : null } | { 'sold' : null }],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];