/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductCategory = IDL.Variant({
  'home' : IDL.Null,
  'local' : IDL.Null,
  'fashion' : IDL.Null,
  'electronics' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'buy' : IDL.Null,
  'land' : IDL.Null,
  'rent' : IDL.Null,
  'sell' : IDL.Null,
  'farmhouse' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ConsultationType = IDL.Variant({
  'webDesign' : IDL.Null,
  'investmentPlanning' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const ConsultationBooking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'userName' : IDL.Text,
  'serviceType' : ConsultationType,
  'contact' : IDL.Text,
  'userId' : IDL.Principal,
  'preferredDate' : IDL.Text,
  'notes' : IDL.Text,
});
export const EnquiryType = IDL.Variant({
  'realEstate' : IDL.Variant({
    'buy' : IDL.Null,
    'land' : IDL.Null,
    'rent' : IDL.Null,
    'sell' : IDL.Null,
    'farmhouse' : IDL.Null,
  }),
  'webDesign' : IDL.Variant({
    'websiteDev' : IDL.Null,
    'businessPromo' : IDL.Null,
    'socialMedia' : IDL.Null,
  }),
  'education' : IDL.Variant({
    'legal' : IDL.Null,
    'career' : IDL.Null,
    'guidance' : IDL.Null,
  }),
  'investmentPlanning' : IDL.Variant({
    'startup' : IDL.Null,
    'business' : IDL.Null,
    'property' : IDL.Null,
    'fundManagement' : IDL.Null,
  }),
  'interiorDecor' : IDL.Variant({
    'pvcPanel' : IDL.Null,
    'ceiling' : IDL.Null,
    'homeInterior' : IDL.Null,
  }),
});
export const Time = IDL.Int;
export const Enquiry = IDL.Record({
  'id' : IDL.Nat,
  'contactInfo' : IDL.Text,
  'enquiryType' : EnquiryType,
  'userId' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'userId' : IDL.Principal,
  'timestamp' : Time,
  'items' : IDL.Vec(CartItem),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : ProductCategory,
  'price' : IDL.Nat,
});
export const PropertyListing = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'rented' : IDL.Null,
    'active' : IDL.Null,
    'sold' : IDL.Null,
  }),
  'title' : IDL.Text,
  'contact' : IDL.Text,
  'propertyType' : PropertyType,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'areaSize' : IDL.Nat,
  'budget' : IDL.Nat,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'walletBalance' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, ProductCategory, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addPropertyListing' : IDL.Func(
      [IDL.Text, PropertyType, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookConsultation' : IDL.Func(
      [ConsultationType, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'clearMyCart' : IDL.Func([], [], []),
  'createOrder' : IDL.Func([], [IDL.Nat], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(ConsultationBooking)], ['query']),
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllPropertyListings' : IDL.Func(
      [],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFilteredProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getFilteredPropertiesByBudget' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'getMyBookings' : IDL.Func([], [IDL.Vec(ConsultationBooking)], ['query']),
  'getMyCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getMyEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyPropertyListings' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
  'getSortedProductsByPrice' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getSortedPropertiesByBudget' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitEnquiry' : IDL.Func([EnquiryType, IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateProductStock' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updatePropertyStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'rented' : IDL.Null,
          'active' : IDL.Null,
          'sold' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductCategory = IDL.Variant({
    'home' : IDL.Null,
    'local' : IDL.Null,
    'fashion' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'buy' : IDL.Null,
    'land' : IDL.Null,
    'rent' : IDL.Null,
    'sell' : IDL.Null,
    'farmhouse' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ConsultationType = IDL.Variant({
    'webDesign' : IDL.Null,
    'investmentPlanning' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const ConsultationBooking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'userName' : IDL.Text,
    'serviceType' : ConsultationType,
    'contact' : IDL.Text,
    'userId' : IDL.Principal,
    'preferredDate' : IDL.Text,
    'notes' : IDL.Text,
  });
  const EnquiryType = IDL.Variant({
    'realEstate' : IDL.Variant({
      'buy' : IDL.Null,
      'land' : IDL.Null,
      'rent' : IDL.Null,
      'sell' : IDL.Null,
      'farmhouse' : IDL.Null,
    }),
    'webDesign' : IDL.Variant({
      'websiteDev' : IDL.Null,
      'businessPromo' : IDL.Null,
      'socialMedia' : IDL.Null,
    }),
    'education' : IDL.Variant({
      'legal' : IDL.Null,
      'career' : IDL.Null,
      'guidance' : IDL.Null,
    }),
    'investmentPlanning' : IDL.Variant({
      'startup' : IDL.Null,
      'business' : IDL.Null,
      'property' : IDL.Null,
      'fundManagement' : IDL.Null,
    }),
    'interiorDecor' : IDL.Variant({
      'pvcPanel' : IDL.Null,
      'ceiling' : IDL.Null,
      'homeInterior' : IDL.Null,
    }),
  });
  const Time = IDL.Int;
  const Enquiry = IDL.Record({
    'id' : IDL.Nat,
    'contactInfo' : IDL.Text,
    'enquiryType' : EnquiryType,
    'userId' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'userId' : IDL.Principal,
    'timestamp' : Time,
    'items' : IDL.Vec(CartItem),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : ProductCategory,
    'price' : IDL.Nat,
  });
  const PropertyListing = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'rented' : IDL.Null,
      'active' : IDL.Null,
      'sold' : IDL.Null,
    }),
    'title' : IDL.Text,
    'contact' : IDL.Text,
    'propertyType' : PropertyType,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'areaSize' : IDL.Nat,
    'budget' : IDL.Nat,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'walletBalance' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, ProductCategory, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addPropertyListing' : IDL.Func(
        [
          IDL.Text,
          PropertyType,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookConsultation' : IDL.Func(
        [ConsultationType, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'clearMyCart' : IDL.Func([], [], []),
    'createOrder' : IDL.Func([], [IDL.Nat], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(ConsultationBooking)], ['query']),
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllPropertyListings' : IDL.Func(
        [],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFilteredProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getFilteredPropertiesByBudget' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getMyBookings' : IDL.Func([], [IDL.Vec(ConsultationBooking)], ['query']),
    'getMyCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getMyEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyPropertyListings' : IDL.Func(
        [],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getSortedProductsByPrice' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getSortedPropertiesByBudget' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitEnquiry' : IDL.Func(
        [EnquiryType, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateProductStock' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updatePropertyStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'rented' : IDL.Null,
            'active' : IDL.Null,
            'sold' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };