/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type EnquiryType = {
    __kind__: "realEstate";
    realEstate: Variant_buy_land_rent_sell_farmhouse;
} | {
    __kind__: "webDesign";
    webDesign: Variant_websiteDev_businessPromo_socialMedia;
} | {
    __kind__: "education";
    education: Variant_legal_career_guidance;
} | {
    __kind__: "investmentPlanning";
    investmentPlanning: Variant_startup_business_property_fundManagement;
} | {
    __kind__: "interiorDecor";
    interiorDecor: Variant_pvcPanel_ceiling_homeInterior;
};
export interface PropertyListing {
    id: bigint;
    status: Variant_rented_active_sold;
    title: string;
    contact: string;
    propertyType: PropertyType;
    owner: Principal;
    description: string;
    areaSize: bigint;
    budget: bigint;
    location: string;
}
export interface Enquiry {
    id: bigint;
    contactInfo: string;
    enquiryType: EnquiryType;
    userId: Principal;
    message: string;
    timestamp: Time;
}
export interface Order {
    id: bigint;
    status: OrderStatus;
    total: bigint;
    userId: Principal;
    timestamp: Time;
    items: Array<CartItem>;
}
export interface ConsultationBooking {
    id: bigint;
    status: BookingStatus;
    userName: string;
    serviceType: ConsultationType;
    contact: string;
    userId: Principal;
    preferredDate: string;
    notes: string;
}
export interface CartItem {
    productId: bigint;
    quantity: bigint;
}
export interface Product {
    id: bigint;
    title: string;
    description: string;
    stock: bigint;
    imageUrl: string;
    category: ProductCategory;
    price: bigint;
}
export interface UserProfile {
    contact: string;
    name: string;
    walletBalance: bigint;
}
export enum BookingStatus {
    scheduled = "scheduled",
    cancelled = "cancelled",
    completed = "completed"
}
export enum ConsultationType {
    webDesign = "webDesign",
    investmentPlanning = "investmentPlanning"
}
export enum OrderStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed"
}
export enum ProductCategory {
    home = "home",
    local = "local",
    fashion = "fashion",
    electronics = "electronics"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_buy_land_rent_sell_farmhouse {
    buy = "buy",
    land = "land",
    rent = "rent",
    sell = "sell",
    farmhouse = "farmhouse"
}
export enum Variant_legal_career_guidance {
    legal = "legal",
    career = "career",
    guidance = "guidance"
}
export enum Variant_pvcPanel_ceiling_homeInterior {
    pvcPanel = "pvcPanel",
    ceiling = "ceiling",
    homeInterior = "homeInterior"
}
export enum Variant_rented_active_sold {
    rented = "rented",
    active = "active",
    sold = "sold"
}
export enum Variant_startup_business_property_fundManagement {
    startup = "startup",
    business = "business",
    property = "property",
    fundManagement = "fundManagement"
}
export enum Variant_websiteDev_businessPromo_socialMedia {
    websiteDev = "websiteDev",
    businessPromo = "businessPromo",
    socialMedia = "socialMedia"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProduct(title: string, category: ProductCategory, price: bigint, description: string, imageUrl: string, stock: bigint): Promise<bigint>;
    addPropertyListing(title: string, propertyType: PropertyType, location: string, budget: bigint, areaSize: bigint, description: string, contact: string): Promise<bigint>;
    addToCart(productId: bigint, quantity: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookConsultation(serviceType: ConsultationType, userName: string, contact: string, preferredDate: string, notes: string): Promise<bigint>;
    clearMyCart(): Promise<void>;
    createOrder(): Promise<bigint>;
    getAllBookings(): Promise<Array<ConsultationBooking>>;
    getAllEnquiries(): Promise<Array<Enquiry>>;
    getAllOrders(): Promise<Array<Order>>;
    getAllProducts(): Promise<Array<Product>>;
    getAllPropertyListings(): Promise<Array<PropertyListing>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFilteredProductsByCategory(category: ProductCategory): Promise<Array<Product>>;
    getFilteredPropertiesByBudget(minBudget: bigint, maxBudget: bigint): Promise<Array<PropertyListing>>;
    getMyBookings(): Promise<Array<ConsultationBooking>>;
    getMyCart(): Promise<Array<CartItem>>;
    getMyEnquiries(): Promise<Array<Enquiry>>;
    getMyOrders(): Promise<Array<Order>>;
    getMyPropertyListings(): Promise<Array<PropertyListing>>;
    getSortedProductsByPrice(ascOrder: boolean): Promise<Array<Product>>;
    getSortedPropertiesByBudget(ascOrder: boolean): Promise<Array<PropertyListing>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitEnquiry(enquiryType: EnquiryType, message: string, contactInfo: string): Promise<bigint>;
    updateBookingStatus(bookingId: bigint, newStatus: BookingStatus): Promise<void>;
    updateOrderStatus(orderId: bigint, newStatus: OrderStatus): Promise<void>;
    updateProductStock(productId: bigint, newStock: bigint): Promise<void>;
    updatePropertyStatus(propertyId: bigint, newStatus: Variant_rented_active_sold): Promise<void>;
}
import type { BookingStatus as _BookingStatus, CartItem as _CartItem, ConsultationBooking as _ConsultationBooking, ConsultationType as _ConsultationType, Enquiry as _Enquiry, EnquiryType as _EnquiryType, Order as _Order, OrderStatus as _OrderStatus, Product as _Product, ProductCategory as _ProductCategory, PropertyListing as _PropertyListing, PropertyType as _PropertyType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProduct(arg0: string, arg1: ProductCategory, arg2: bigint, arg3: string, arg4: string, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, to_candid_ProductCategory_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, to_candid_ProductCategory_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addPropertyListing(arg0: string, arg1: PropertyType, arg2: string, arg3: bigint, arg4: bigint, arg5: string, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPropertyListing(arg0, to_candid_PropertyType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPropertyListing(arg0, to_candid_PropertyType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addToCart(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookConsultation(arg0: ConsultationType, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bookConsultation(to_candid_ConsultationType_n7(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookConsultation(to_candid_ConsultationType_n7(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async clearMyCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearMyCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearMyCart();
            return result;
        }
    }
    async createOrder(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder();
            return result;
        }
    }
    async getAllBookings(): Promise<Array<ConsultationBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEnquiries(): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEnquiries();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEnquiries();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPropertyListings(): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPropertyListings();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPropertyListings();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilteredProductsByCategory(arg0: ProductCategory): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredProductsByCategory(to_candid_ProductCategory_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredProductsByCategory(to_candid_ProductCategory_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilteredPropertiesByBudget(arg0: bigint, arg1: bigint): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredPropertiesByBudget(arg0, arg1);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredPropertiesByBudget(arg0, arg1);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBookings(): Promise<Array<ConsultationBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCart(): Promise<Array<CartItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCart();
            return result;
        }
    }
    async getMyEnquiries(): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEnquiries();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEnquiries();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPropertyListings(): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPropertyListings();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPropertyListings();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSortedProductsByPrice(arg0: boolean): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedProductsByPrice(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedProductsByPrice(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSortedPropertiesByBudget(arg0: boolean): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedPropertiesByBudget(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedPropertiesByBudget(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitEnquiry(arg0: EnquiryType, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEnquiry(to_candid_EnquiryType_n44(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEnquiry(to_candid_EnquiryType_n44(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n50(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n50(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n52(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n52(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProductStock(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductStock(arg0, arg1);
            return result;
        }
    }
    async updatePropertyStatus(arg0: bigint, arg1: Variant_rented_active_sold): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePropertyStatus(arg0, to_candid_variant_n54(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePropertyStatus(arg0, to_candid_variant_n54(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BookingStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ConsultationBooking_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConsultationBooking): ConsultationBooking {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ConsultationType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConsultationType): ConsultationType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_EnquiryType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnquiryType): EnquiryType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Enquiry_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Enquiry): Enquiry {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyListing_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyListing): PropertyListing {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    userName: string;
    serviceType: _ConsultationType;
    contact: string;
    userId: Principal;
    preferredDate: string;
    notes: string;
}): {
    id: bigint;
    status: BookingStatus;
    userName: string;
    serviceType: ConsultationType;
    contact: string;
    userId: Principal;
    preferredDate: string;
    notes: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n12(_uploadFile, _downloadFile, value.status),
        userName: value.userName,
        serviceType: from_candid_ConsultationType_n14(_uploadFile, _downloadFile, value.serviceType),
        contact: value.contact,
        userId: value.userId,
        preferredDate: value.preferredDate,
        notes: value.notes
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    contactInfo: string;
    enquiryType: _EnquiryType;
    userId: Principal;
    message: string;
    timestamp: _Time;
}): {
    id: bigint;
    contactInfo: string;
    enquiryType: EnquiryType;
    userId: Principal;
    message: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        contactInfo: value.contactInfo,
        enquiryType: from_candid_EnquiryType_n19(_uploadFile, _downloadFile, value.enquiryType),
        userId: value.userId,
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    total: bigint;
    userId: Principal;
    timestamp: _Time;
    items: Array<_CartItem>;
}): {
    id: bigint;
    status: OrderStatus;
    total: bigint;
    userId: Principal;
    timestamp: Time;
    items: Array<CartItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n29(_uploadFile, _downloadFile, value.status),
        total: value.total,
        userId: value.userId,
        timestamp: value.timestamp,
        items: value.items
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    description: string;
    stock: bigint;
    imageUrl: string;
    category: _ProductCategory;
    price: bigint;
}): {
    id: bigint;
    title: string;
    description: string;
    stock: bigint;
    imageUrl: string;
    category: ProductCategory;
    price: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        stock: value.stock,
        imageUrl: value.imageUrl,
        category: from_candid_ProductCategory_n34(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        rented: null;
    } | {
        active: null;
    } | {
        sold: null;
    };
    title: string;
    contact: string;
    propertyType: _PropertyType;
    owner: Principal;
    description: string;
    areaSize: bigint;
    budget: bigint;
    location: string;
}): {
    id: bigint;
    status: Variant_rented_active_sold;
    title: string;
    contact: string;
    propertyType: PropertyType;
    owner: Principal;
    description: string;
    areaSize: bigint;
    budget: bigint;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n39(_uploadFile, _downloadFile, value.status),
        title: value.title,
        contact: value.contact,
        propertyType: from_candid_PropertyType_n40(_uploadFile, _downloadFile, value.propertyType),
        owner: value.owner,
        description: value.description,
        areaSize: value.areaSize,
        budget: value.budget,
        location: value.location
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): BookingStatus {
    return "scheduled" in value ? BookingStatus.scheduled : "cancelled" in value ? BookingStatus.cancelled : "completed" in value ? BookingStatus.completed : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    webDesign: null;
} | {
    investmentPlanning: null;
}): ConsultationType {
    return "webDesign" in value ? ConsultationType.webDesign : "investmentPlanning" in value ? ConsultationType.investmentPlanning : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    realEstate: {
        buy: null;
    } | {
        land: null;
    } | {
        rent: null;
    } | {
        sell: null;
    } | {
        farmhouse: null;
    };
} | {
    webDesign: {
        websiteDev: null;
    } | {
        businessPromo: null;
    } | {
        socialMedia: null;
    };
} | {
    education: {
        legal: null;
    } | {
        career: null;
    } | {
        guidance: null;
    };
} | {
    investmentPlanning: {
        startup: null;
    } | {
        business: null;
    } | {
        property: null;
    } | {
        fundManagement: null;
    };
} | {
    interiorDecor: {
        pvcPanel: null;
    } | {
        ceiling: null;
    } | {
        homeInterior: null;
    };
}): {
    __kind__: "realEstate";
    realEstate: Variant_buy_land_rent_sell_farmhouse;
} | {
    __kind__: "webDesign";
    webDesign: Variant_websiteDev_businessPromo_socialMedia;
} | {
    __kind__: "education";
    education: Variant_legal_career_guidance;
} | {
    __kind__: "investmentPlanning";
    investmentPlanning: Variant_startup_business_property_fundManagement;
} | {
    __kind__: "interiorDecor";
    interiorDecor: Variant_pvcPanel_ceiling_homeInterior;
} {
    return "realEstate" in value ? {
        __kind__: "realEstate",
        realEstate: from_candid_variant_n21(_uploadFile, _downloadFile, value.realEstate)
    } : "webDesign" in value ? {
        __kind__: "webDesign",
        webDesign: from_candid_variant_n22(_uploadFile, _downloadFile, value.webDesign)
    } : "education" in value ? {
        __kind__: "education",
        education: from_candid_variant_n23(_uploadFile, _downloadFile, value.education)
    } : "investmentPlanning" in value ? {
        __kind__: "investmentPlanning",
        investmentPlanning: from_candid_variant_n24(_uploadFile, _downloadFile, value.investmentPlanning)
    } : "interiorDecor" in value ? {
        __kind__: "interiorDecor",
        interiorDecor: from_candid_variant_n25(_uploadFile, _downloadFile, value.interiorDecor)
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    land: null;
} | {
    rent: null;
} | {
    sell: null;
} | {
    farmhouse: null;
}): Variant_buy_land_rent_sell_farmhouse {
    return "buy" in value ? Variant_buy_land_rent_sell_farmhouse.buy : "land" in value ? Variant_buy_land_rent_sell_farmhouse.land : "rent" in value ? Variant_buy_land_rent_sell_farmhouse.rent : "sell" in value ? Variant_buy_land_rent_sell_farmhouse.sell : "farmhouse" in value ? Variant_buy_land_rent_sell_farmhouse.farmhouse : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    websiteDev: null;
} | {
    businessPromo: null;
} | {
    socialMedia: null;
}): Variant_websiteDev_businessPromo_socialMedia {
    return "websiteDev" in value ? Variant_websiteDev_businessPromo_socialMedia.websiteDev : "businessPromo" in value ? Variant_websiteDev_businessPromo_socialMedia.businessPromo : "socialMedia" in value ? Variant_websiteDev_businessPromo_socialMedia.socialMedia : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    legal: null;
} | {
    career: null;
} | {
    guidance: null;
}): Variant_legal_career_guidance {
    return "legal" in value ? Variant_legal_career_guidance.legal : "career" in value ? Variant_legal_career_guidance.career : "guidance" in value ? Variant_legal_career_guidance.guidance : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startup: null;
} | {
    business: null;
} | {
    property: null;
} | {
    fundManagement: null;
}): Variant_startup_business_property_fundManagement {
    return "startup" in value ? Variant_startup_business_property_fundManagement.startup : "business" in value ? Variant_startup_business_property_fundManagement.business : "property" in value ? Variant_startup_business_property_fundManagement.property : "fundManagement" in value ? Variant_startup_business_property_fundManagement.fundManagement : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pvcPanel: null;
} | {
    ceiling: null;
} | {
    homeInterior: null;
}): Variant_pvcPanel_ceiling_homeInterior {
    return "pvcPanel" in value ? Variant_pvcPanel_ceiling_homeInterior.pvcPanel : "ceiling" in value ? Variant_pvcPanel_ceiling_homeInterior.ceiling : "homeInterior" in value ? Variant_pvcPanel_ceiling_homeInterior.homeInterior : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
}): OrderStatus {
    return "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    home: null;
} | {
    local: null;
} | {
    fashion: null;
} | {
    electronics: null;
}): ProductCategory {
    return "home" in value ? ProductCategory.home : "local" in value ? ProductCategory.local : "fashion" in value ? ProductCategory.fashion : "electronics" in value ? ProductCategory.electronics : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rented: null;
} | {
    active: null;
} | {
    sold: null;
}): Variant_rented_active_sold {
    return "rented" in value ? Variant_rented_active_sold.rented : "active" in value ? Variant_rented_active_sold.active : "sold" in value ? Variant_rented_active_sold.sold : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Enquiry>): Array<Enquiry> {
    return value.map((x)=>from_candid_Enquiry_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PropertyListing>): Array<PropertyListing> {
    return value.map((x)=>from_candid_PropertyListing_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConsultationBooking>): Array<ConsultationBooking> {
    return value.map((x)=>from_candid_ConsultationBooking_n10(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_ConsultationType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConsultationType): _ConsultationType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_EnquiryType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnquiryType): _EnquiryType {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    home: null;
} | {
    local: null;
} | {
    fashion: null;
} | {
    electronics: null;
} {
    return value == ProductCategory.home ? {
        home: null
    } : value == ProductCategory.local ? {
        local: null
    } : value == ProductCategory.fashion ? {
        fashion: null
    } : value == ProductCategory.electronics ? {
        electronics: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_buy_land_rent_sell_farmhouse): {
    buy: null;
} | {
    land: null;
} | {
    rent: null;
} | {
    sell: null;
} | {
    farmhouse: null;
} {
    return value == Variant_buy_land_rent_sell_farmhouse.buy ? {
        buy: null
    } : value == Variant_buy_land_rent_sell_farmhouse.land ? {
        land: null
    } : value == Variant_buy_land_rent_sell_farmhouse.rent ? {
        rent: null
    } : value == Variant_buy_land_rent_sell_farmhouse.sell ? {
        sell: null
    } : value == Variant_buy_land_rent_sell_farmhouse.farmhouse ? {
        farmhouse: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "realEstate";
    realEstate: Variant_buy_land_rent_sell_farmhouse;
} | {
    __kind__: "webDesign";
    webDesign: Variant_websiteDev_businessPromo_socialMedia;
} | {
    __kind__: "education";
    education: Variant_legal_career_guidance;
} | {
    __kind__: "investmentPlanning";
    investmentPlanning: Variant_startup_business_property_fundManagement;
} | {
    __kind__: "interiorDecor";
    interiorDecor: Variant_pvcPanel_ceiling_homeInterior;
}): {
    realEstate: {
        buy: null;
    } | {
        land: null;
    } | {
        rent: null;
    } | {
        sell: null;
    } | {
        farmhouse: null;
    };
} | {
    webDesign: {
        websiteDev: null;
    } | {
        businessPromo: null;
    } | {
        socialMedia: null;
    };
} | {
    education: {
        legal: null;
    } | {
        career: null;
    } | {
        guidance: null;
    };
} | {
    investmentPlanning: {
        startup: null;
    } | {
        business: null;
    } | {
        property: null;
    } | {
        fundManagement: null;
    };
} | {
    interiorDecor: {
        pvcPanel: null;
    } | {
        ceiling: null;
    } | {
        homeInterior: null;
    };
} {
    return value.__kind__ === "realEstate" ? {
        realEstate: to_candid_variant_n4(_uploadFile, _downloadFile, value.realEstate)
    } : value.__kind__ === "webDesign" ? {
        webDesign: to_candid_variant_n49(_uploadFile, _downloadFile, value.webDesign)
    } : value.__kind__ === "education" ? {
        education: to_candid_variant_n48(_uploadFile, _downloadFile, value.education)
    } : value.__kind__ === "investmentPlanning" ? {
        investmentPlanning: to_candid_variant_n47(_uploadFile, _downloadFile, value.investmentPlanning)
    } : value.__kind__ === "interiorDecor" ? {
        interiorDecor: to_candid_variant_n46(_uploadFile, _downloadFile, value.interiorDecor)
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pvcPanel_ceiling_homeInterior): {
    pvcPanel: null;
} | {
    ceiling: null;
} | {
    homeInterior: null;
} {
    return value == Variant_pvcPanel_ceiling_homeInterior.pvcPanel ? {
        pvcPanel: null
    } : value == Variant_pvcPanel_ceiling_homeInterior.ceiling ? {
        ceiling: null
    } : value == Variant_pvcPanel_ceiling_homeInterior.homeInterior ? {
        homeInterior: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_startup_business_property_fundManagement): {
    startup: null;
} | {
    business: null;
} | {
    property: null;
} | {
    fundManagement: null;
} {
    return value == Variant_startup_business_property_fundManagement.startup ? {
        startup: null
    } : value == Variant_startup_business_property_fundManagement.business ? {
        business: null
    } : value == Variant_startup_business_property_fundManagement.property ? {
        property: null
    } : value == Variant_startup_business_property_fundManagement.fundManagement ? {
        fundManagement: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_legal_career_guidance): {
    legal: null;
} | {
    career: null;
} | {
    guidance: null;
} {
    return value == Variant_legal_career_guidance.legal ? {
        legal: null
    } : value == Variant_legal_career_guidance.career ? {
        career: null
    } : value == Variant_legal_career_guidance.guidance ? {
        guidance: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_websiteDev_businessPromo_socialMedia): {
    websiteDev: null;
} | {
    businessPromo: null;
} | {
    socialMedia: null;
} {
    return value == Variant_websiteDev_businessPromo_socialMedia.websiteDev ? {
        websiteDev: null
    } : value == Variant_websiteDev_businessPromo_socialMedia.businessPromo ? {
        businessPromo: null
    } : value == Variant_websiteDev_businessPromo_socialMedia.socialMedia ? {
        socialMedia: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
} {
    return value == BookingStatus.scheduled ? {
        scheduled: null
    } : value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} {
    return value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_rented_active_sold): {
    rented: null;
} | {
    active: null;
} | {
    sold: null;
} {
    return value == Variant_rented_active_sold.rented ? {
        rented: null
    } : value == Variant_rented_active_sold.active ? {
        active: null
    } : value == Variant_rented_active_sold.sold ? {
        sold: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConsultationType): {
    webDesign: null;
} | {
    investmentPlanning: null;
} {
    return value == ConsultationType.webDesign ? {
        webDesign: null
    } : value == ConsultationType.investmentPlanning ? {
        investmentPlanning: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
